/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.jbequinn.poc.piglatin;

import java.util.Scanner;

public class App {
	public static void main(String[] args) {
		System.out.print("Enter some text: ");
		String text = new Scanner(System.in).nextLine();

		String[] input = text.split(" ");
		String[] output = new String[input.length];
		for (int wordIndex = 0; wordIndex < input.length; wordIndex++) {
			new ConversionVisitor.ConversationVisitors().convert(wordIndex, input, output);
		}

		System.out.println("The output is: " + String.join(" ", output));
	}
}
