/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.jbequinn.poc.piglatin;

public class App {
	public static void main(String[] args) {
		String text = System.console().readLine("Enter some text: ");

		String[] input = text.split(" ");
		String[] output = new String[input.length];
		new ConversionVisitor.ConversationVisitors().convert(0, input, output);

		System.out.println("The output is: " + String.join(" ", output));
	}
}
